const ActionTypes = {
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  API_CALL_BEGIN: "API_CALL_BEGIN",
  API_CALL_FAILED: "API_CALL_FAILED",
  LOAD_AUTHORS_SUCCESS: "LOAD_AUTHORS_SUCCESS"
};

module.exports = ActionTypes;
